apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debug-team-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/attach"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/ephemeralcontainers"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-team-binding
subjects:
- kind: Group
  name: debug-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: debug-team-role
  apiGroup: rbac.authorization.k8s.io
---
# For normal user
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devs-team-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/attach"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/ephemeralcontainers"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devs-team-binding
subjects:
- kind: Group
  name: devs-team
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: devs-team-role
  apiGroup: rbac.authorization.k8s.io
